name: Test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    -
      uses: actions/checkout@v2.3.5
    -
      name: Load Go version
      id: go-version
      run: |
        echo ::set-output name=go-version::$(sed 's/^.*://' .github/go/Dockerfile)
    -
      uses: actions/setup-go@v2
      id: setup-go
      with:
        go-version: ${{ steps.go-version.outputs.go-version }}
    -
      run: go build
